"""prompts 包 — 导出所有 Prompt 模板"""
from prompts.profile_prompts import (
    PROMPT_PROFILE_COLD_START,
    PROMPT_PROFILE_EXTRACT,
    PROMPT_PROFILE_COMPARE,
)
from prompts.path_prompts import PROMPT_PATH_GENERATE
from prompts.resource_prompts import (
    PROMPT_GENERATE_DOCUMENT,
    PROMPT_GENERATE_MERMAID,
    PROMPT_GENERATE_EXERCISE_SET,
    PROMPT_GENERATE_CODE_CASE,
    PROMPT_GENERATE_READING,
)
from prompts.validation_prompts import (
    PROMPT_VALIDATE_RESOURCE,
    PROMPT_VALIDATE_EXERCISE,
)
from prompts.chat_prompts import (
    PROMPT_INTENT_CLASSIFY,
    PROMPT_RAG_QA,
    PROMPT_COLD_START_GUIDE,
)

__all__ = [
    "PROMPT_PROFILE_COLD_START",
    "PROMPT_PROFILE_EXTRACT",
    "PROMPT_PROFILE_COMPARE",
    "PROMPT_PATH_GENERATE",
    "PROMPT_GENERATE_DOCUMENT",
    "PROMPT_GENERATE_MERMAID",
    "PROMPT_GENERATE_EXERCISE_SET",
    "PROMPT_GENERATE_CODE_CASE",
    "PROMPT_GENERATE_READING",
    "PROMPT_VALIDATE_RESOURCE",
    "PROMPT_VALIDATE_EXERCISE",
    "PROMPT_INTENT_CLASSIFY",
    "PROMPT_RAG_QA",
    "PROMPT_COLD_START_GUIDE",
]
